###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:
  webserver:
    build:
      context: .
      dockerfile: phpdocker/nginx/Dockerfile
    container_name: short_link_test_task_webserver
    working_dir: /application
    ports:
      - "80:80"
    depends_on:
      - php-fpm
  php-fpm:
    build:
      context: .
      dockerfile: phpdocker/php-cli/Dockerfile
    restart: unless-stopped
    container_name: short_link_test_task_fpm
    working_dir: /application
    environment:
      TZ: "Europe/Kiev"
    volumes:
      - .:/application
  postgres:
    image: postgres:9.5-alpine
    container_name: short_link_test_task_postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-secret}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - "5433:5432"
volumes:
  pgdata: